// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "ddk-rn.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RNDdkRnSpec.h"

@interface DdkRn : NSObject <NativeDdkRnSpec>
#else
#import <React/RCTBridgeModule.h>

@interface DdkRn : NSObject <RCTBridgeModule>
#endif

@end