#ifndef BENNYBLADER_DDKRN_H
#define BENNYBLADER_DDKRN_H
// Generated by uniffi-bindgen-react-native
#include <ReactCommon/CallInvoker.h>
#include <cstdint>
#include <jsi/jsi.h>

namespace bennyblader_ddkrn {
using namespace facebook;

uint8_t installRustCrate(jsi::Runtime &runtime,
                         std::shared_ptr<react::CallInvoker> callInvoker);
uint8_t cleanupRustCrate(jsi::Runtime &runtime);
} // namespace bennyblader_ddkrn

#endif /* BENNYBLADER_DDKRN_H */