// Generated by uniffi-bindgen-react-native
#include "bennyblader-ddk-rn.h"
#include "ddk_ffi.hpp"

namespace bennyblader_ddkrn {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeDdkFfi::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}